### ISSUE TITLE
Possible to invert display like the micropython version ?

### ISSUE THREAD

**Issue by markbirss** [zhcong/ST7302-for-arduino#2]
Hi

Is is at all possible to also invert eh display like with the Micropython version ?
https://github.com/zhcong/ST7302-for-micropython

![image](https://github.com/zhcong/ST7302-for-arduino/assets/22388007/42e837b4-11d5-48d5-8859-c198cd839e0d)

**Comment by zhcong** [comment]
you mean this function?:
``` c++
    void inversion_off();
    void inversion_on();
```
see in [ST7302SPI.h](https://github.com/zhcong/ST7302-for-arduino/blob/main/libraries/ST7302SPI/ST7302SPI.h)
it works in my screen.

**Comment by markbirss** [comment]
@zhcong  thank you
